version: "3.8"

services:
  loudbalancer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loudbalancer
    environment:
      - CONFIG_PATH=/config/config.yml
    ports:
      - "8080:8080"

  # Запуск тестовых бекендов для демонстрации
  backend1:
    build:
      context: apache_benchmark/test_backends/backend1
      dockerfile: Dockerfile
    container_name: backend1
    ports:
      - "8081:8081"

  backend2:
    build:
      context: apache_benchmark/test_backends/backend2
      dockerfile: Dockerfile
    container_name: backend2
    ports:
      - "8082:8082"
