env: "dev" # dev, prod
server:
  port: ":8080"
  backends:
      - http://localhost:8081
      - http://localhost:8082
      - http://localhost:8083
      - http://localhost:8084
      - http://localhost:8085
      - http://localhost:8086
      - http://localhost:8087
      - http://localhost:8088