env: "dev" # Окружение: dev | prod

server:
  port: ":8080"                      # Порт для HTTP-сервера
  timeouts:
    read:  "10s"                      # ReadTimeout
    write: "10s"                      # WriteTimeout
    idle:  "60s"                      # IdleTimeout
  health_interval: "30s"             # Интервал health check пул бекендов
  backends:
    - http://backend1:8081
    - http://backend2:8082

rate_limit:
  default_capacity:   2500               # Начальная вместимость
  default_rps:        100                # Токенов в секунду
  replenish_interval: "1s"            # Интервал пополнения токенов
