env: "dev" # Окружение: dev | prod

server:
  port: ":8080"                      # Порт для HTTP-сервера
  timeouts:
    read:  "10s"                      # ReadTimeout
    write: "10s"                      # WriteTimeout
    idle:  "60s"                      # IdleTimeout
  health_interval: "30s"             # Интервал health check пул бекендов
  backends:
    - "http://localhost:8081"
    - "http://localhost:8082"

rate_limit:
  default_capacity:   3                # Начальная вместимость ведра
  default_rps:        1                # Токенов в секунду
  replenish_interval: "1s"            # Интервал пополнения токенов

features:
  healthcheck: true                   # Включить периодический health check
  rate_limit:  true                   # Включить rate limiting
